#!/usr/bin/env python
from waflib.extras.test_base import summary

def options(opt):
    opt.load('compiler_cxx')
    opt.load('gtest')


def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('gtest')


def build(bld):
    bld(
        features='cxx cxxprogram gtest',
        source='test.cpp',
        target='hate_test',
        use = 'hate_inc',
    )

    bld.add_post_fun(summary)
