@Library("jenlib") _

withCcache() {
	wafDefaultPipeline(projects: ["hate"],
	                   container: [app: "wafer-nodev"],
	                   notificationChannel: "#softies")

	wafDefaultPipeline(projects: ["hate"],
	                   container: [app: "dls-core"],
	                   notificationChannel: "#softies")
}
