@Library("jenlib") _

wafDefaultPipeline(projects: ["hate"],
                   container: [app: "wafer"],
                   notificationChannel: "#softies")

wafDefaultPipeline(projects: ["hate"],
                   container: [app: "dls-core"],
                   notificationChannel: "#softies")
