@Library("jenlib") _

wafDefaultPipeline(projects: ["hate"],
                   container: [app: "visionary-wafer"],
                   notificationChannel: "#softies")

wafDefaultPipeline(projects: ["hate"],
                   container: [app: "visionary-dls"],
                   notificationChannel: "#softies")